"""
 Constants for users app
"""

""" Log Constants """

# Users app common
USER_NOT_FOUND = 'USER_NOT_FOUND'

# User Create API
USER_CREATE_API_INIT = 'USER_CREATE_API_INIT'
USER_CREATE_API_SUCCESS = 'USER_CREATE_API_SUCCESS'
USER_CREATE_API_ERROR = 'USER_CREATE_API_ERROR'

# User List API
USER_LIST_API_INIT = 'USER_LIST_API_INIT'
USER_LIST_API_WITH_PAGINATION = 'USER_LIST_API_WITH_PAGINATION'
USER_LIST_API_WITHOUT_PAGINATION = 'USER_LIST_API_WITHOUT_PAGINATION'
USER_LIST_API_SUCCESS = 'USER_LIST_API_SUCCESS'

# User Retrieve API
USER_RETRIEVE_API_INIT = 'USER_RETRIEVE_API_INIT'
USER_RETRIEVE_API_SUCCESS = 'USER_RETRIEVE_API_SUCCESS'

# User Update API
USER_UPDATE_API_INIT = 'USER_UPDATE_API_INIT'
USER_UPDATE_API_IS_PARTIAL = 'USER_UPDATE_API_IS_PARTIAL'
USER_UPDATE_API_SUCCESS = 'USER_UPDATE_API_SUCCESS'
USER_UPDATE_API_ERROR = 'USER_UPDATE_API_ERROR'

# User Partial Update API
USER_PARTIAL_UPDATE_API_INIT = 'USER_PARTIAL_UPDATE_API_INIT'

# User Destroy API
USER_DESTROY_API_INIT = 'USER_DESTROY_API_INIT'
USER_DESTROY_API_SUCCESS = 'USER_DESTROY_API_SUCCESS'
